### ISSUE TITLE
Create touch-enabled movement

### ISSUE THREAD

**Issue by cdubz** [cdubz/phaser-space-flyer#10]
#9 is the larger request for mobile support, but let's explore movement options that don't require the keyboard. Does any system like this ultimately mean that combat has to be AI to some degree?

**Comment by cdubz** [comment]
Created **touch-camera** branch to work on this. Using the [Kinetic Scrolling plugin](https://github.com/jdnichollsc/Phaser-Kinetic-Scrolling-Plugin) now for the camera movement, it works well and has very clean code.

**Comment by cdubz** [comment]
@bovard I need you math skillz. How to make the ship turn to face the crosshair point for movement? everything else for this branch is done, methinks.

**Comment by bovard** [comment]
I'll take a look

**Comment by bovard** [comment]
Looking good. The only thing I don't think you'd want (if you had multiple ships) is for the camera to follow the moving ship.

**Comment by cdubz** [comment]
Yeah, agreed. I just wanted to test out using follow/unfollow methods. It works pretty smoothly.

Thanks for the help! I gotta brush up my damn math knowledge, I used to be good at that shit hah.

Finished with #11 and #12
