### ISSUE TITLE
Turn 'n Shoot

### ISSUE THREAD

**Issue by cdubz** [cdubz/phaser-space-flyer#6]
It is possible to fire (spacebar) while accelerating (up arrow) and turning _right_ (right arrow), but it is not possible to fire while accelerating and turning _left_ (left arrow).

**Comment by bovard** [comment]
http://gaming.stackexchange.com/questions/6669/how-do-i-remove-the-limit-on-pc-keyboard-button-presses

> In order to save money, keyboard manufacturers often put many keys on the same "circuit" of sorts within the wiring of the keyboard. This prevents multiple keys in the same region of the keyboard from being pressed simultaneously. Sometimes it even prevents more than 2 keys at all from across the whole keyboard being pressed at once. Often the shift, ctrl, and alt keys are not within this limitation, so you can hold shift and press 2 other keys at once and it will still work fine.

**Comment by bovard** [comment]
Works on my machine :)

**Comment by bovard** [comment]
![](http://www.hanselman.com/blog/content/binary/WindowsLiveWriter/IntroducingRockScroll_C29C/works-on-my-machine-starburst_3.png)

**Comment by bovard** [comment]
Won't Fix

**Comment by cdubz** [comment]
Fucking circuits bro.
